# Generated by Django 5.1.4 on 2025-01-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('duedate', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('upcoming', 'upcoming'), ('completed', 'completed')], default='pending', max_length=10)),
            ],
        ),
    ]
